version: "3.8"

services:
  frontend:
    image: ${ACR_REGISTRY}/${ACR_NAMESPACE}/ui:$TAG
    container_name: frontend-container
    ports:
      - 80
    restart: always
    env_file:
      - /app/config/frontend.env
        # 绑定宿主机目录
    volumes:
      - /server/data/frontend/dist:/dist
    # volumes:
    #   - frontend-data:/dist
    #   # 将静态文件挂载到共享卷
    command: ["tail", "-f", "/dev/null"] # 保持容器运行但不提供服务
  backend:
    image: ${ACR_REGISTRY}/${ACR_NAMESPACE}/server:$TAG
    container_name: backend-container
    ports:
      - 3000
    # volumes:
    #   - backend-data:/data
    volumes:
      - /server/data/backend:/data
    restart: always
    env_file:
      - /app/config/backend.env
# volumes:
#   backend-data:
#   frontend-data:
