version: "3.8"

services:
  frontend:
    image: ${{ secrets.ACR_REGISTRY }}/${{ secrets.ACR_NAMESPACE }}/ui:$TAG
    container_name: frontend-container
    ports:
      - "${FRONTEND_PORT}:80"
    restart: always
    env_file:
      - /app/config/frontend.env
    volumes:
      - frontend-data:/dist # 将静态文件挂载到共享卷
    command: ["sh", "-c", "tail -f /dev/null"] # 保持容器运行但不提供服务
  backend:
    image: ${{ secrets.ACR_REGISTRY }}/${{ secrets.ACR_NAMESPACE }}/server:$TAG
    container_name: backend-container
    ports:
      - "${BACKEND_PORT}:3000"
    volumes:
      - backend-data:/data
    restart: always
    env_file:
      - /app/config/backend.env

volumes:
  backend-data:
  frontend-data:
