version: "3.8"

services:
  frontend:
    image: ${ACR_REGISTRY}/${ACR_NAMESPACE}/ui:$TAG
    container_name: frontend-container
    ports:
      - "8080:8080"
    restart: always
    env_file:
      - /app/config/frontend.env
        # 绑定宿主机目录
    # volumes:
    #   - /server/data/frontend/dist:/usr/share/nginx/html # 匹配Nginx默认路径
    command: ["nginx", "-g", "daemon off;"] # 确保命令存在
    # volumes:
    #   - frontend-data:/dist
    #   # 将静态文件挂载到共享卷
    # command: ["nginx", "-g", "daemon off;"]
  backend:
    image: ${ACR_REGISTRY}/${ACR_NAMESPACE}/server:$TAG
    container_name: backend-container
    ports:
      - "3000:3000"
    # volumes:
    #   - backend-data:/data
    volumes:
      - /server/data/backend:/data
    restart: always
    env_file:
      - /app/config/backend.env
    # 容器启动时执行的命令
    command: ["yarn", "start:prod"]
# volumes:
#   backend-data:
#   frontend-data:
