name: Docker CI/CD to Aliyun

on:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. 检出代码
      - name: Checkout code
        uses: actions/checkout@v4
      # 2. 配置阿里云镜像加速器（关键步骤）
      - name: Setup Docker mirror
        run: |
          echo '{
            "registry-mirrors": ["https://dockerproxy.com"]
          }' | sudo tee /etc/docker/daemon.json
          sudo systemctl restart docker || true
      # 3. 登录阿里云容器镜像服务
      - name: Login to Aliyun ACR
        uses: aliyun/acr-login@v1.0.6
        with:
          login-server: ${{ secrets.ACR_REGISTRY }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      #4. 构建前端镜像
      - name: Build ui Image
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          cd ui
          docker build -t ${{ secrets.ACR_REGISTRY }}/${{ secrets.ACR_NAMESPACE }}/ui:$IMAGE_TAG .
          docker push ${{ secrets.ACR_REGISTRY }}/${{ secrets.ACR_NAMESPACE }}/ui:$IMAGE_TAG

      # 5.构建后端镜像
      - name: Build server Image
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          cd server
          docker build -t ${{ secrets.ACR_REGISTRY }}/${{ secrets.ACR_NAMESPACE }}/server:$IMAGE_TAG .
          docker push ${{ secrets.ACR_REGISTRY }}/${{ secrets.ACR_NAMESPACE }}/server:$IMAGE_TAG

      # 测试 SSH 连接
      - name: Test SSH Connection
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "SSH 连接成功！"
            whoami
            pwd
      # 6.部署脚本
      - name: Sync deployment scripts
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "scripts/*,deploy/docker-compose.prod.yml" # 同步scripts目录,docker-compose
          target: "/app/deploy/" # 目标位置
      # 7. 通过 SSH 部署到 ECS
      - name: Deploy to ECS
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # 设置环境变量
             export ACR_REGISTRY="${{ secrets.ACR_REGISTRY }}"
             export ACR_NAMESPACE="${{ secrets.ACR_NAMESPACE }}"
             # 确保脚本可执行
             chmod +x /app/deploy/scripts/deploy.sh

             # 添加调试信息
             echo "当前目录: $(pwd)"
             echo "脚本路径: /app/deploy/scripts/deploy.sh"
             ls -la /app/deploy/scripts

             # 执行部署脚本
            /app/deploy/scripts/deploy.sh \
             "${{ github.sha }}" \
             "$ACR_REGISTRY" \
             "$ACR_NAMESPACE" 

             # 验证部署结果
             docker ps -a
             curl -I http://localhost:80
